---
version: 0.2
env:
  variables:
    GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS
    SQLALCHEMY_DATABASE_URI: $SQLALCHEMY_DATABASE_URI
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - export REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
  build:
    commands:
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - docker build  -t $IMAGE_REPO_NAME:$IMAGE_TAG . 
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo $SQLALCHEMY_DATABASE_URI
      - echo $SECRET_KEY
      - echo $userpools
      - docker run -d --name $IMAGE_REPO_NAME -e SQLALCHEMY_DATABASE_URI=$SQLALCHEMY_DATABASE_URI -e SECRET_KEY=$SECRET_KEY -e userpools=$userpools $IMAGE_REPO_NAME:$IMAGE_TAG
      - docker exec $IMAGE_REPO_NAME alembic upgrade head
      - docker stop $IMAGE_REPO_NAME
artifacts:
  files: imagedefinitions.json
