"""Change nfl team to use espn id (int)

Revision ID: 089d6bc0e17a
Revises: bc2f088b1396
Create Date: 2022-08-13 16:06:24.464561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089d6bc0e17a'
down_revision = 'bc2f088b1396'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nflteam', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('nflteam_espn_id_key', 'nflteam', type_='unique')
    op.create_unique_constraint(None, 'nflteam', ['id'])
    op.drop_column('nflteam', 'espn_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nflteam', sa.Column('espn_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'nflteam', type_='unique')
    op.create_unique_constraint('nflteam_espn_id_key', 'nflteam', ['espn_id'])
    op.drop_column('nflteam', 'id')
    # ### end Alembic commands ###
