"""picture_url

Revision ID: 0a9c5d6d802b
Revises: 10a910db3500
Create Date: 2023-08-27 17:56:31.813399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a9c5d6d802b'
down_revision = '10a910db3500'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'picture_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('picture_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
