"""Testing db connection

Revision ID: 0df932206d92
Revises: 75d4e26c47bd
Create Date: 2022-08-13 14:18:00.442662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0df932206d92'
down_revision = '75d4e26c47bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
