"""removing stadium dependency

Revision ID: 1f1a31e7bca6
Revises: 0a9c5d6d802b
Create Date: 2023-08-29 22:26:18.750220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f1a31e7bca6'
down_revision = '0a9c5d6d802b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('game_stadium_id_fkey', 'game', type_='foreignkey')
    op.drop_column('game', 'stadium_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('stadium_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('game_stadium_id_fkey', 'game', 'stadium', ['stadium_id'], ['id'])
    # ### end Alembic commands ###
