"""Change stadium id to integer part 1

Revision ID: 31dc477a9299
Revises: 0df932206d92
Create Date: 2022-08-13 15:53:54.998289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '31dc477a9299'
down_revision = '0df932206d92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('game_stadium_id_fkey', 'game', type_='foreignkey')
    op.drop_column('game', 'stadium_id')
    op.add_column('stadium', sa.Column('espn_id', sa.Integer(), nullable=False))
    op.drop_column('stadium', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stadium', sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_column('stadium', 'espn_id')
    op.add_column('game', sa.Column('stadium_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('game_stadium_id_fkey', 'game', 'stadium', ['stadium_id'], ['id'])
    # ### end Alembic commands ###
