"""Adding provider to users

Revision ID: 366810cbdc9a
Revises: 763fff11a72b
Create Date: 2022-08-01 19:46:34.310564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366810cbdc9a'
down_revision = '763fff11a72b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
