"""conference and division from nfl team

Revision ID: 3bfbb66139b9
Revises: 1f1a31e7bca6
Create Date: 2023-08-29 23:04:52.699002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bfbb66139b9'
down_revision = '1f1a31e7bca6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nflteam', 'division')
    op.drop_column('nflteam', 'conference')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nflteam', sa.Column('conference', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('nflteam', sa.Column('division', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
