"""Convert game_id to int, part 2

Revision ID: 43257e3f4c5b
Revises: dc26dafbe529
Create Date: 2022-08-14 14:59:24.963397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '43257e3f4c5b'
down_revision = 'dc26dafbe529'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pick_game_id_fkey', 'pick', type_='foreignkey')
    op.drop_column('game', 'id')
    op.drop_column('pick', 'game_id')
    op.add_column('pick', sa.Column('espn_game_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pick', 'game', ['espn_game_id'], ['espn_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pick', sa.Column('game_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pick', type_='foreignkey')
    op.create_foreign_key('pick_game_id_fkey', 'pick', 'game', ['game_id'], ['id'])
    op.drop_column('pick', 'espn_game_id')
    op.add_column('game', sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
