"""user id to string

Revision ID: 617ab5d31dbb
Revises: a5e3b73c6486
Create Date: 2022-08-22 22:53:33.772861

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '617ab5d31dbb'
down_revision = 'a5e3b73c6486'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id',
               existing_type=postgresql.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id',
               existing_type=sa.String(),
               type_=postgresql.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
