"""Major project restructure

Revision ID: 75d4e26c47bd
Revises: ca735fad071e
Create Date: 2022-08-07 19:42:29.671636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d4e26c47bd'
down_revision = 'ca735fad071e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
