"""Adding provider to users

Revision ID: 763fff11a72b
Revises: 44e3f3d14c1b
Create Date: 2022-08-01 19:44:19.151555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763fff11a72b'
down_revision = '44e3f3d14c1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'provider')
    # ### end Alembic commands ###
