"""Remove roof type from stadiums since espn doesn't have it

Revision ID: 82a8f922123f
Revises: 089d6bc0e17a
Create Date: 2022-08-13 16:16:55.011169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82a8f922123f'
down_revision = '089d6bc0e17a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stadium', 'roof_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stadium', sa.Column('roof_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
