"""is admin default to false

Revision ID: 82bb04423245
Revises: bfa774bd699f
Create Date: 2022-08-22 23:29:46.593170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82bb04423245'
down_revision = 'bfa774bd699f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
