"""Convert game_id to int, part 3

Revision ID: 8f6840123d3c
Revises: 43257e3f4c5b
Create Date: 2022-08-14 15:00:53.746977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f6840123d3c'
down_revision = '43257e3f4c5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('pick_espn_game_id_fkey', 'pick', type_='foreignkey')
    op.drop_constraint('game_espn_id_key', 'game', type_='unique')
    op.create_unique_constraint(None, 'game', ['id'])
    op.drop_column('game', 'espn_id')
    op.add_column('pick', sa.Column('game_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pick', 'game', ['game_id'], ['id'])
    op.drop_column('pick', 'espn_game_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pick', sa.Column('espn_game_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pick', type_='foreignkey')
    op.create_foreign_key('pick_espn_game_id_fkey', 'pick', 'game', ['espn_game_id'], ['espn_id'])
    op.drop_column('pick', 'game_id')
    op.add_column('game', sa.Column('espn_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'game', type_='unique')
    op.create_unique_constraint('game_espn_id_key', 'game', ['espn_id'])
    op.drop_column('game', 'id')
    # ### end Alembic commands ###
