"""Make conference and division nullable on nfl team

Revision ID: a0566844707a
Revises: 82a8f922123f
Create Date: 2022-08-13 17:05:40.590386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0566844707a'
down_revision = '82a8f922123f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
