"""Major project restructure

Revision ID: ca735fad071e
Revises: a512cc540642
Create Date: 2022-08-07 19:08:09.849635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca735fad071e'
down_revision = 'a512cc540642'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
