"""Change nfl team to use espn id (int)

Revision ID: db9ec888ecba
Revises: e6161a17ac75
Create Date: 2022-08-13 16:04:55.958514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db9ec888ecba'
down_revision = 'e6161a17ac75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nflteam', sa.Column('espn_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'nflteam', ['espn_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nflteam', type_='unique')
    op.drop_column('nflteam', 'espn_id')
    # ### end Alembic commands ###
