"""Convert game_id to int, part 1

Revision ID: dc26dafbe529
Revises: a0566844707a
Create Date: 2022-08-14 14:53:35.885466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc26dafbe529'
down_revision = 'a0566844707a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('espn_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'game', ['espn_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game', type_='unique')
    op.drop_column('game', 'espn_id')
    # ### end Alembic commands ###
