"""Adding odds, part 2

Revision ID: e65a3e7facc6
Revises: 108ec4ac2d2c
Create Date: 2022-08-14 16:12:39.517374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e65a3e7facc6'
down_revision = '108ec4ac2d2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'odds', ['id'])
    op.drop_constraint('odds_game_id_fkey', 'odds', type_='foreignkey')
    op.drop_column('odds', 'game_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odds', sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('odds_game_id_fkey', 'odds', 'game', ['game_id'], ['id'])
    op.drop_constraint(None, 'odds', type_='unique')
    # ### end Alembic commands ###
